{
  "button":[
    {	
      "name":"游戏",
      "sub_button":[
      {
      "type":"click",
      "name":"刷新信息",
      "key":"刷新信息"
      },
      {
      "type":"click",
      "name":"历史信息",
      "key":"历史信息"
      },
      {
      "type":"click",
      "name":"帮助信息",
      "key":"帮助信息"
      },
      {
      "type":"click",
      "name":"开始游戏",
      "key":"开始游戏"
      },
      {
      "type":"click",
      "name":"退出游戏",
      "key":"退出游戏"
      }]
    },
    {
      "name":"规则",
      "sub_button":[
      {
      "type":"view",
      "name":"新手规则",
      "url":"http://mp.weixin.qq.com/s/F5lFJWhuTIeD5aldJu15gQ"
      },
      {
      "type":"view",
      "name":"规则视频",
      "url":"http://mp.weixin.qq.com/s/gGVc5GVWldyr9t-k-gfbpQ"
      },
      {
      "type":"view",
      "name":"FAQ",
      "url":"http://mp.weixin.qq.com/s/KvnYYUULnl1Qq6ifElbJsg"
      },
      {
      "type":"view",
      "name":"宣传视频",
      "url":"http://v.youku.com/v_show/id_XMjg4ODgyNTYyMA==.html?spm=a2h3j.8428770.3416059.1"
      },
      {
      "type":"view",
      "name":"背景故事",
      "url":"http://mp.weixin.qq.com/s/PeH9gfbhLZw0uvNc8q9muQ"
      }]
    },
    {
      "name":"更多",
      "sub_button":[
      {
      "type":"view",
      "name":"下载古董APP",
      "url":"http://mp.weixin.qq.com/s/1q9ZCjQm0n7bGDxR2H-vxw"
      },
      {
      "type":"view",
      "name":"盒闪公众号",
      "url":"http://mp.weixin.qq.com/s/lU7fT8RtPQLBXlBOnTYJPA"
      },
      {	
      "type":"view",
      "name":"盒闪微店",
      "url":"https://weidian.com/?userid=1226993362&wfr=qfriend&ifr=shopdetail"
      },
      {
      "type":"click",
      "name":"盒闪淘宝",
      "key":"盒闪淘宝"
      },
      {
      "type":"click",
      "name":"玩家交流",
      "key":"玩家交流"  
      }]
    }]
}